### ISSUE TITLE
Susquehanna does not run on Windows

### ISSUE THREAD

**Issue by alexdcramer** [alexdcramer/Susquehanna#18]
Susquehanna does not appear to be functional on non-Linux operating systems. This appears to be an issue with JavaFX components not being properly bundled. This issue appears both on the Windows 7 VM and on Windows 11. Here is the log, name is redacted as it was not run on my computer:

```
D:\>susquehanna.exe
[DEBUG]    [2024-09-17 12:11:01] - IPA temp file created at C:\Users\[REDACTED]\AppData\Local\Temp\101829834213845273860148587460.tmp
[DEBUG]    [2024-09-17 12:11:01] - Starting loading screen at 2024-09-17T16:11:01.823223100Z
[DEBUG]    [2024-09-17 12:11:02] - Finished loading screen at 2024-09-17T16:11:02.207073700Z
[INFO]     [2024-09-17 12:11:02] - Starting application...
[DEBUG]    [2024-09-17 12:11:02] - IPA phonology system successfully verified!
[INFO]     [2024-09-17 12:11:02] - Loading scenes...
[INFO]     [2024-09-17 12:11:02] - Found 0 language(s)
[DEBUG]    [2024-09-17 12:11:02] - Language(s) found:
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: C:\Program Files\Java\jdk-23\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Users\[REDACTED]\AppData\Local\Microsoft\WindowsApps;C:\Users\[REDACTED]\.dotnet\tools;C:\Program Files\Java\jdk-23\bin;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2442)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2066)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:163)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
        at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
        at javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
        at javafx.scene.web.WebView.<init>(WebView.java:260)
        at net.oijon.susquehanna.gui.scenes.file.ReportBugPage.<init>(ReportBugPage.java:21)
        at net.oijon.susquehanna.App.start(App.java:96)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
```

**Comment by alexdcramer** [comment]
Fixed.
